sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1
  wechat:
    appid: wx0b73407b6fb00692
    secret: 8b3057514ec6d654d8d321efe4190ef5
#   阿里云OSS
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucketName: web-tilas-jxt
